name: build for release

on:
  release:
    types: [published]

jobs:
  build-mod:
    name: Build Mod
    runs-on: ubuntu-latest
    env:
      MODKIT_VERSION: 0.9.3.4-beta
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Fetch dependencies
      run: dotnet restore ./EcoBulletinBoardMod/EcoBulletinBoardMod.csproj
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Cache Eco dlls
      id: cache-eco-dlls
      uses: actions/cache@v2
      with:
        path: ./eco-dlls
        key: ${{ env.MODKIT_VERSION }}-ref-dlls
    - name: Download Eco dlls
      if: steps.cache-eco-dlls.outputs.cache-hit != 'true'
      run: sh fetch-eco-reference-assemblies.sh
    - name: Build
      run: dotnet build ./EcoBulletinBoardMod/EcoBulletinBoardMod.csproj --configuration Release --no-restore
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: mod-binaries-${{github.event.release.tag_name}}
        path: EcoBulletinBoardMod/bin/Release/netcoreapp3.1/EcoBulletinBoardMod.*
  deploy:
    name: Upload Release Assets
    needs:
    - build-mod
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact (mod)
        id: download-mod
        uses: actions/download-artifact@v2
        with:
          name: mod-binaries-${{github.event.release.tag_name}}
      - name: Upload release asset (mod)
        id: upload-release-asset-mod
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ${{steps.download-mod.outputs.download-path}}/EcoBulletinBoardMod.dll
          asset_name: EcoBulletinBoardMod.dll
          asset_content_type: application/octet-stream
